// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseRequester.Persistence.Requests;

#nullable disable

namespace PurchaseRequester.Persistence.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20220522033307_wip")]
    partial class wip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("PurchaseRequester.Domain.Requests.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("catagory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
